Switching to https://github.com/heroku/heroku-buildpack-nodejs#v105
Indeed application failed to start (according to "heroku logs") with:
app[web.1]: A hook (`session`) failed to load!
app[web.1]: Could not load Connect session adapter :: connect-redis
app[web.1]:     at Function.Module._load (module.js:437:25)
app[web.1]: Error from adapter:
app[web.1]:     at Function.Module._resolveFilename (module.js:485:15)
app[web.1]: Error: Cannot find module '/app/node_modules/connect-redis'
app[web.1]:     at Module.require (module.js:513:17)
app[web.1]:     at require (internal/module.js:11:18)
app[web.1]:     at Hook.initialize (/app/node_modules/sails/lib/hooks/session/index.js:220:32)
app[web.1]:     at /app/node_modules/sails/node_modules/async/lib/async.js:52:16
app[web.1]:     at /app/node_modules/sails/lib/hooks/index.js:88:16
app[web.1]:     at Hook.wrapper [as initialize] (/app/node_modules/@sailshq/lodash/lib/index.js:3250:19)
app[web.1]:     at Immediate.taskComplete (/app/node_modules/sails/node_modules/async/lib/async.js:541:13)
app[web.1]:     at /app/node_modules/sails/node_modules/async/lib/async.js:548:17
app[web.1]:     at /app/node_modules/sails/node_modules/async/lib/async.js:542:17
app[web.1]:     at _arrayEach (/app/node_modules/sails/node_modules/async/lib/async.js:85:13)
app[web.1]:     at runCallback (timers.js:800:20)
app[web.1]:     at tryOnImmediate (timers.js:762:5)
app[web.1]: Try running the following command in your project's root directory:
app[web.1]:     at processImmediate [as _immediateCallback] (timers.js:733:5)
app[web.1]:
app[web.1]: Do you have the Connect session adapter installed in this project?
app[web.1]: A hook (`orm`) failed to load!
app[web.1]: npm install connect-redis
app[web.1]: (Note: Make sure the version of the Connect adapter you install is compatible with Express 3/Sails v0.10)

Moreover, https://github.com/mbuchetics/heroku-buildpack-nodejs-grunt mentions:
Note: this buildpack is no longer maintained